In [97]:
import numpy as np
import math

In [104]:
class Task:
    def __init__(self, num_plants, num_dcs, num_retailers, num_customers, coord_bound=1000):
        self.num_plants = num_plants
        self.num_dcs = num_dcs
        self.num_retailers = num_retailers
        self.num_customers = num_customers

        #site coordinates
        self.plant_coords = np.random.uniform(-coord_bound, coord_bound, size=(self.num_plants, 2))
        self.dc_coords = np.random.uniform(-coord_bound, coord_bound, size=(self.num_dcs, 2))
        self.retailer_coords = np.random.uniform(-coord_bound, coord_bound, size=(self.num_retailers, 2))
        self.customer_coords = np.random.uniform(-coord_bound, coord_bound, size=(self.num_customers, 2))

        #shipping cost
        self.x1 = np.zeros((self.num_plants, self.num_dcs))
        self.x2 = np.zeros((self.num_dcs, self.num_retailers))
        self.x3 = np.zeros((self.num_retailers, self.num_customers))
        self.x4 = np.zeros((self.num_plants, self.num_customers))
        self.x5 = np.zeros((self.num_dcs, self.num_customers))
        self.x6 = np.zeros((self.num_plants, self.num_retailers))

    def gen_cost(self, delivery_type):
        pass

    def dist(self, site_a_coords, site_b_coords):
        print(site_a_coords)
        print(site_b_coords)

        def single_dist(a, b):
            return math.sqrt(((a[0] - b[0]) ** 2) + ((a[1] - b[1]) ** 2))

        for i in range(len(site_a_coords)):
            for j in range(len(site_b_coords)):
                print("{0} ".format(single_dist(site_a_coords[i], site_b_coords[j])))
            print("")
            
        site_a_coords_x = site_a_coords[:, 0]
        site_a_coords_y = site_a_coords[:, 1]
        
        site_b_coords_x = site_b_coords[:, 0]
        site_b_coords_y = site_b_coords[:, 1]

        print(site_a_coords_x.strides)

        dist_mat_shape = (site_a_coords.shape[0], site_b_coords.shape[0])

        site_a_coords_x_ = np.lib.stride_tricks.as_strided(site_a_coords_x, dist_mat_shape, (16, 0))
        site_b_coords_x_ = np.lib.stride_tricks.as_strided(site_b_coords_x, dist_mat_shape, (0, 16))
        x_diffs = (site_a_coords_x_ - site_b_coords_x) ** 2

        site_a_coords_y_ = np.lib.stride_tricks.as_strided(site_a_coords_y, dist_mat_shape, (16, 0))
        site_b_coords_y_ = np.lib.stride_tricks.as_strided(site_b_coords_y, dist_mat_shape, (0, 16))
        y_diffs = (site_a_coords_y_ - site_b_coords_y) ** 2
        
        dist_mat = np.sqrt(x_diffs + y_diffs)
        return dist_mat
    
        

In [105]:
task = Task(3, 4, 5, 6, coord_bound=10.0)


plant -> dc -> retailer -> customer

In [106]:
task.dist(task.plant_coords, task.customer_coords)

[[ 9.33200432 -0.29151358]
 [-2.98237513  8.64484951]
 [-2.65173461  8.92096568]]
[[-5.48918507 -6.02134266]
 [-3.59242953 -5.89097987]
 [-6.77276352  8.84005514]
 [ 4.37470794  7.50675209]
 [-8.26126779 -1.05614356]
 [-5.48118557 -6.95374956]]
15.890204409490394
(16,)


array([[15.89020441, 14.08527646, 18.51348412,  9.24054841, 17.60988025,
        16.24241309],
       [14.87888736, 14.54862544,  3.79541162,  7.44459113, 11.04427336,
        15.79747912],
       [15.20932949, 14.84178688,  4.12182311,  7.16734923, 11.44594125,
        16.12489928]])