In [162]:
%load_ext autoreload
%autoreload 2
import numpy as np
from entity import Entity
from task import Task
from plant import Plant
from dc import DC
from retailer import Retailer
from customer import Customer
from indi import Individual
from crossover import *
from mutation import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [163]:
task = Task(3, 5, 5, 6)

In [164]:
for _ in range(task.num_plants):
	coord_x, coord_y = np.random.randint(0, 10), np.random.randint(0, 10)
	output = np.random.randint(0, 1000)
	task.lst_plants.append(Plant(coord_x, coord_y, output))
for _ in range(task.num_dcs):
	coord_x, coord_y = np.random.randint(0, 10), np.random.randint(0, 10)
	capacity = np.random.randint(0, 100)
	lease_cost = np.random.randint(100)
	open_cost = np.random.randint(100)
	task.lst_dcs.append(DC(coord_x, coord_y, capacity, lease_cost, open_cost))
for _ in range(task.num_retailers):
	coord_x, coord_y = np.random.randint(0, 10), np.random.randint(0, 10)
	capacity = np.random.randint(0, 100)
	lease_cost = np.random.randint(100)
	open_cost = np.random.randint(100)
	task.lst_retailers.append(Retailer(coord_x, coord_y, capacity, lease_cost, open_cost))
for _ in range(task.num_customers):
	coord_x, coord_y = np.random.randint(0, 10), np.random.randint(0, 10)
	demand = np.random.randint(0, 10)
	task.lst_customers.append(Customer(coord_x, coord_y, demand))

In [165]:
for p in task.lst_plants:
    print(p)

(3, 6)
output: 305
(1, 9)
output: 245
(8, 0)
output: 93


In [166]:
for dc in task.lst_dcs:
    print(dc)

(2, 3)
capacity: 20
lease cost: 3
open cost: 73
(7, 9)
capacity: 48
lease cost: 8
open cost: 93
(1, 6)
capacity: 98
lease cost: 0
open cost: 43
(5, 5)
capacity: 70
lease cost: 76
open cost: 30
(8, 7)
capacity: 24
lease cost: 16
open cost: 24


In [167]:
for rt in task.lst_retailers:
    print(rt)

(7, 2)
capacity: 1
lease cost: 68
open cost: 95
(6, 5)
capacity: 69
lease cost: 69
open cost: 68
(7, 2)
capacity: 49
lease cost: 15
open cost: 57
(5, 2)
capacity: 39
lease cost: 98
open cost: 97
(6, 7)
capacity: 2
lease cost: 98
open cost: 56


In [168]:
for ct in task.lst_customers:
    print(ct)

(1, 5)
demand: 1
(1, 6)
demand: 3
(0, 5)
demand: 4
(9, 2)
demand: 8
(9, 3)
demand: 3
(2, 4)
demand: 1


In [169]:
indi = Individual(task)

In [170]:
print(indi)

Customer 0:
Plant 1 -> DC 1 -> Retailer 3
Customer 1:
Plant 1 -> DC 1 -> Retailer 1
Customer 2:
Plant 1 -> DC 0 -> Retailer 1
Customer 3:
Plant 2 -> DC 1 -> Retailer 0
Customer 4:
Plant 1 -> DC 1 -> Retailer 1
Customer 5:
Plant 2 -> DC 2 -> Retailer 0



In [171]:
mut = InsertionMutation()
print(mut(indi))

Retailer 0 capacity violated!
Customer 0:
Plant 1 -> DC 1 -> Retailer 3
Customer 1:
Plant 1 -> DC 1 -> Retailer 1
Customer 2:
Plant 2 -> DC 1 -> Retailer 0
Customer 3:
Plant 1 -> DC 0 -> Retailer 1
Customer 4:
Plant 1 -> DC 1 -> Retailer 1
Customer 5:
Plant 2 -> DC 2 -> Retailer 0



In [172]:
cross = TwoCutCrossover()
pa = Individual(task)
pb = Individual(task)
off = cross(pa, pb)

9
15
[0 3 2 1 1 4 2 4 4 2 2 0 2 1 0 2 2 2]
[2 1 1 0 0 2 0 1 4 0 1 4 2 3 2 2 2 2]
[0 3 2 1 1 4 2 4 4 0 1 4 2 3 2 2 2 2]
Retailer 4 capacity violated!


In [173]:
print(pa)
print(pb)
print(off)

Customer 0:
Plant 0 -> DC 3 -> Retailer 2
Customer 1:
Plant 1 -> DC 1 -> Retailer 4
Customer 2:
Plant 2 -> DC 4 -> Retailer 4
Customer 3:
Plant 2 -> DC 2 -> Retailer 0
Customer 4:
Plant 2 -> DC 1 -> Retailer 0
Customer 5:
Plant 2 -> DC 2 -> Retailer 2

Customer 0:
Plant 2 -> DC 1 -> Retailer 1
Customer 1:
Plant 0 -> DC 0 -> Retailer 2
Customer 2:
Plant 0 -> DC 1 -> Retailer 4
Customer 3:
Plant 0 -> DC 1 -> Retailer 4
Customer 4:
Plant 2 -> DC 3 -> Retailer 2
Customer 5:
Plant 2 -> DC 2 -> Retailer 2

Customer 0:
Plant 0 -> DC 3 -> Retailer 2
Customer 1:
Plant 1 -> DC 1 -> Retailer 4
Customer 2:
Plant 2 -> DC 4 -> Retailer 4
Customer 3:
Plant 0 -> DC 1 -> Retailer 4
Customer 4:
Plant 2 -> DC 3 -> Retailer 2
Customer 5:
Plant 2 -> DC 2 -> Retailer 2

